version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=festivals
    ports: 
      - "5432:5432"

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/festivals?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres

