apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-api
  name: auth-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: aimeric/festivals-app:latest
        ports:
        - containerPort: 8080
    